spring:
  datasource:
    username: postgres
    password: compasso
    url: jdbc:postgresql://localhost:5432/checkouttest
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
